### ISSUE TITLE
Smooth dark color issue

### ISSUE THREAD

**Issue by sarneeh** [krismuniz/minimo#14]
I don't know if it's a problem with my PC or the extension. Take a look at how the "Smooth dark" background color looks on my screen (notice the bottom rectangle with a slightly different color than the rest):

![Screenshot](https://i.imgur.com/hcUpFVI.gif)

Is it just me or is it a common problem?

**Comment by krismuniz** [comment]
Interestingly enough, this is actually the third time I hear about this issue. I will reproduce it and try to fix it as soon as possible.

**Comment by krismuniz** [comment]
Hi @sarneeh, I managed to reproduce your issue on macOS. 

Apparently since Chromium 68+ there have been several conflicts between the user's monitor color profile (defaults to unmanaged). On macOS it's producing this weird issue where colors are rendered differently for no reason.

I found a fix though. Forcing the sRGB color profile chrome://flags#force-color-profile should do the trick.

**Comment by sarneeh** [comment]
@krismuniz Yeah, the issue was kinda weird, as it only appeared on the black theme. Firstly I thought that it's something with my eyes 😄 

Switching the color profile fixed the problem for me :) Thank you! What do you think about adding some info in the README about this issue?

**Comment by krismuniz** [comment]
Yeah I think it might be wise to add it to the README just in case. At least until Chromium fixes it.

**Comment by sarneeh** [comment]
@krismuniz I've created a PR to address this: #15
